In [2]:
import tensorflow as tf

In [3]:
tensor = tf.constant([[1,2,3],
                      [4,5,6]])

In [4]:
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [5]:
tensor.shape

TensorShape([2, 3])

### Tensor Size

In [7]:
#Tensor Size
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

### Tensor Rank
Tensor Rank, No. of Dimensions
- Rank 0: Scalars. Tensors of rank 0 represent single values.
- Rank 1: Vectors. Tensors of rank 1 have one dimension and represent arrays of values.
- Rank 2: Matrices. Tensors of rank 2 have two dimensions and represent 2D arrays of values.
- Rank 3 and above: Tensors of rank 3 or higher have three or more dimensions and represent higher-dimensional arrays of values.

In [9]:
scaler = tf.constant(5)
vector = tf.constant([2,4])
matrix = tf.constant([[1,2,3],
                      [4,5,6]])
tensor_3d = tf.constant([[[7,8,9,10],
                          [11,12,13,14]],
                         [[15,16,17,18],
                          [19,20,21,22]]])

In [12]:
tf.rank(scaler)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [13]:
tf.rank(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [14]:
tf.rank(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [15]:
tf.rank(tensor_3d)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [17]:
rank_scaler = tf.rank(scaler)

In [18]:
rank_scaler.numpy()

np.int32(0)

### Tensor Dimensions
Tensor dimension refers to the length along a particular axis of a tensor.

In [19]:
tensor = tf.constant([[1,2,3],[4,5,6]])
shape = tensor.shape

In [20]:
shape

TensorShape([2, 3])

In [21]:
# Get the length of the first dimension
dim1_length = shape[0]
dim1_length

2

In [22]:
dim2_length = shape[1]
dim2_length

3