In [8]:
import tensorflow as tf

In [10]:
tensor = tf.Variable([1,2,3])

In [14]:
tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [13]:
print(tensor.numpy())

[1 2 3]


In [15]:
const_tensor = tf.constant([1,2,3])

In [16]:
const_tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [17]:
print(const_tensor.numpy())

[1 2 3]


In [18]:
tensor[1].assign(5)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([1, 5, 3], dtype=int32)>

In [ ]:
const_tensor[1].assign(5) #-> error