In [1]:
import numpy as np

In [2]:
scaler = np.array(5)
vector = np.array([1,2,3])
matrix = np.array([[1,2,3],
                   [4,5,6]])
tensor_3d = np.array([[[1,2,3],
                    [4,5,6]],
                   [[7,8,9],
                    [10,11,12]]])

In [3]:
scaler

array(5)

In [6]:
print(vector)

[1 2 3]


In [7]:
import tensorflow as tf

In [8]:
scaler = tf.convert_to_tensor(scaler)
scaler

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [10]:
vector = tf.convert_to_tensor(vector)

In [11]:
print(vector)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [12]:
matrix = tf.convert_to_tensor(matrix)

In [13]:
matrix

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [14]:
tensor_3d = tf.convert_to_tensor(tensor_3d)

In [15]:
tensor_3d

<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>