In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.19.0'

In [3]:
a = tf.constant(3)

In [4]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [5]:
b = tf.constant(4)

In [6]:
b

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [7]:
c = a+b

In [8]:
c

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [9]:
c.numpy()

np.int32(7)

In [10]:
print(c.numpy())

7
