In [12]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
X = np.array([[0, 1], [1, 1], [1, 0], [0, 0]])
y = np.array([0, 1, 2, 0])  # 3 classes: 0, 1, 2

In [14]:
X

array([[0, 1],
       [1, 1],
       [1, 0],
       [0, 0]])

In [15]:
y

array([0, 1, 2, 0])

In [16]:
# create a NN
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Hidden layer
model.add(Dense(3, activation='softmax'))  # Output layer

In [18]:
# computing the model
model.compile(loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [19]:
# train the model
model.fit(X, y, epochs=10)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 458ms/step - accuracy: 0.2500 - loss: 1.3459
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2500 - loss: 1.3349
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.2500 - loss: 1.3271
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.2500 - loss: 1.3206
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.2500 - loss: 1.3150
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.2500 - loss: 1.3098
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.2500 - loss: 1.3050
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.2500 - loss: 1.3005
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.2500 - loss: 1.2962
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.2500 - loss: 1.2921


In [20]:
# Make predictions
predictions = model.predict(X)
print(predictions)  # Output will be probabilities for each class

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[[0.22357437 0.4656597  0.31076586]
 [0.36470452 0.18372294 0.4515725 ]
 [0.43072185 0.15527353 0.4140046 ]
 [0.34023988 0.33150077 0.32825935]]
