In [13]:
import numpy as np

In [14]:
A = np.array([[1,2],[3,4]])

In [15]:
A

array([[1, 2],
       [3, 4]])

In [16]:
B = np.array([[5,6],[7,8]])

In [17]:
B

array([[5, 6],
       [7, 8]])

In [18]:
result = np.dot(A,B)

In [19]:
result

array([[19, 22],
       [43, 50]])