In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("E:\Machine_Learning_Journey\Machine_Learning_Journey\data_sets\social_ads.csv")
data

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [10]:
X = data.drop(columns = ['Purchased'])
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [11]:
y = data['Purchased']
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [12]:
X.shape,y.shape

((400, 2), (400,))

In [13]:
from sklearn.model_selection import train_test_split as tts

In [14]:
X_train,X_test,y_train,y_test = tts(X,y,train_size = 0.75, random_state = 2529)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((300, 2), (100, 2), (300,), (100,))

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
sc = StandardScaler()

In [17]:
dtemp = sc.fit_transform(data)

In [21]:
type(dtemp)

numpy.ndarray

In [22]:
import numpy as np
import matplotlib.pyplot as plt

In [23]:
pd.DataFrame(dtemp)

0         1         2
0   -1.781797 -1.490046 -0.745936
1   -0.253587 -1.460681 -0.745936
2   -1.113206 -0.785290 -0.745936
3   -1.017692 -0.374182 -0.745936
4   -1.781797  0.183751 -0.745936
..        ...       ...       ...
395  0.797057 -0.844019  1.340598
396  1.274623 -1.372587  1.340598
397  1.179110 -1.460681  1.340598
398 -0.158074 -1.078938 -0.745936
399  1.083596 -0.990844  1.340598

[400 rows x 3 columns]

In [28]:
pd.DataFrame(dtemp).describe()

0             1             2
count  4.000000e+02  4.000000e+02  4.000000e+02
mean  -7.105427e-17 -1.776357e-17  1.421085e-16
std    1.001252e+00  1.001252e+00  1.001252e+00
min   -1.877311e+00 -1.607506e+00 -7.459358e-01
25%   -7.550313e-01 -7.852897e-01 -7.459358e-01
50%   -6.256110e-02  7.561451e-03 -7.459358e-01
75%    7.970571e-01  5.361289e-01  1.340598e+00
max    2.134241e+00  2.356750e+00  1.340598e+00

In [47]:
X_train = sc.fit_transform(X_train)

In [30]:
X_test = sc.fit_transform(X_test)

In [31]:
X_train

array([[ 1.08480265, -1.02114931],
       [-0.33385818, -0.81943606],
       [-0.71216774,  0.50610815],
       [ 0.23360615,  0.18913018],
       [-0.23928079,  0.10268165],
       [ 0.61191571,  1.94691707],
       [-1.65794163,  0.07386547],
       [-0.71216774,  0.44847579],
       [-1.75251902,  0.13149783],
       [ 0.13902876,  1.80283618],
       [ 0.42276093,  0.24676254],
       [-1.0904773 ,  0.24676254],
       [-0.23928079, -1.48220817],
       [-0.99589991, -1.48220817],
       [ 1.46311221,  2.06218179],
       [ 1.08480265, -1.25167874],
       [ 0.99022526,  1.80283618],
       [ 0.23360615,  2.03336561],
       [ 1.36853482,  2.26389503],
       [-1.27963207, -0.47364192],
       [ 0.99022526, -1.10759785],
       [-0.71216774,  1.83165236],
       [ 0.7064931 , -1.42457581],
       [ 0.42276093,  0.04504929],
       [ 2.03057654,  1.68757147],
       [-1.37420946, -0.67535517],
       [ 0.89564787, -1.48220817],
       [-0.23928079, -0.70417135],
       [-0.42843557,

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
knn = KNeighborsClassifier(n_neighbors = 5)

In [34]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [50]:
y_pred = knn.predict(X_test)
y_pred

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [48]:
y_test.head(12)

244    0
366    1
163    0
379    1
182    1
84     0
33     0
230    1
104    0
61     0
273    1
248    0
Name: Purchased, dtype: int64

In [51]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [52]:
acs = accuracy_score(y_test,y_pred)
acs

0.89

In [54]:
cr = classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.98      0.85      0.91        66
           1       0.77      0.97      0.86        34

    accuracy                           0.89       100
   macro avg       0.87      0.91      0.88       100
weighted avg       0.91      0.89      0.89       100



In [57]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[56, 10],
       [ 1, 33]], dtype=int64)